name: LXC+DOCKER

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      ksu_variant:
        description: "KSU Variant (Default: Wild)"
        required: true
        default: "Wild"
        type: choice
        options:
          - Wild
          - Next
          - KSU
      build_bypass:
        description: "Bypass verification? (Keep true)"
        required: true
        default: true
        type: boolean

jobs:
  build-kernels-a12:
    name: "Build 5.10.209"
    strategy:
      fail-fast: false
      matrix:
        include:
        - sub_level: "209"
          os_patch_level: "2024-05"

    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_variant: ${{ inputs.ksu_variant }}
      ksu_commit: "wild"
      build_bypass: ${{ inputs.build_bypass }}
